### PR TITLE
Add Morpho Optimizers Adapters

### PR DESCRIPTION
**Pull request by tomrpl**
Adding the following adapters:
- Morpho AaveV2 Optimizer 
- Morpho AaveV3-ETH Optimizer 
- Morpho CompoundV2 Optimizer

### CODE REVIEW

**Comment by bergarces** [comment]
Hey @tomrpl , thanks for submitting the PR and sorry for the delay, but I can't get the branch to run.

There's a comma missing in the package.json, which is an easy fix, but even after that I'm getting building errors with `npm run build`.

Can you please fix them? Also I'd be great if you could make the PR editable by repo authors, as we might want to do some refactors.

**Comment by tomrpl** [comment]
> Hey @tomrpl , thanks for submitting the PR and sorry for the delay, but I can't get the branch to run.
> 
> There's a comma missing in the package.json, which is an easy fix, but even after that I'm getting building errors with `npm run build`.
> 
> Can you please fix them? Also I'd be great if you could make the PR editable by repo authors, as we might want to do some refactors.

**Comment by bergarces** [comment]
Thanks for making the changes. We're in the process of reviewing them before merge. It shouldn't take long.

**Comment by bergarces** [comment]
@tomrpl Apologies for the delay merging, but we have to work on a solution for an issue that has arisen with your adapters.

We have a positions resolver that creates a unique mapping between a protocol token and an adapter, this is done so that protocol tokens can be resolved recursively in case they are layered e.g. wstEth -> stEth -> Eth.

Since your adapters use the same protocol tokens as aave and compound, that's causing an error.

We are discussing how we are going to solve it, but chances are we'll include some sort of property in the adapter that skips adding tokens to the resolver.

**Comment by jpsains** [comment]
image

We had to do a big rebase so merged in a separate PR

**Pull request closed without merging**
