### PR TITLE
[izumi finance] add iziswap adapter

### PR DESCRIPTION
**Pull request by LpcAries**
Hi, this PR is for adding adapter for iZiswap. iZiswap's strategy for managing liquidity is similar to Uniswap V3, so the adapter is modified based on Uniswap V3's adapter. Please check, and if there are any issues, let me know.

### CODE REVIEW

**Comment by jpsains** [comment]
Hey,
Awesome thanks for the PR, we will get it merged this week.
Thanks,
JP

**Comment by jpsains** [comment]
image

Hey, Your adapter has been merged, izumiFinance positions will be reflected in our institutional dashboard this week and will be in MM dashboard in Q1.

Thanks for your support.

**Comment by jpsains** [comment]
hey @LpcAries 

Something we noticed after merging is the arbitrum izumi adapter errors, perhaps one the arbitrum address is incorrect? 

image

**Comment by LpcAries** [comment]
> hey @LpcAries
> 
> Something we noticed after merging is the arbitrum izumi adapter errors, perhaps one the arbitrum address is incorrect?
> 
> image

Sorry, my mistake. And the pr fixed this issue has been commited, pls check.

**Pull request closed without merging**
