### PR TITLE
feat: add Rocket Pool rETH Adapter

### PR DESCRIPTION
**Pull request by nickdoherty**

### CODE REVIEW

**Comment by jpsains** [comment]
Hey @nickdoherty, 

Thanks for the adapter, could you make the PR editable by repo authors please? So we can rebase and make some small edits?

**Comment by nickdoherty** [comment]
Hey @jpsains,

Unfortunately, I don't have the checkbox. Looks like there is an open issue for this on Github.

https://github.com/orgs/community/discussions/5634

The issue lies as our fork lives under an organisation.

Did you just need me to rebase and fix the eslint issues? Or did you need to make additional edits?

**Comment by jpsains** [comment]
Hi @nickdoherty,

No problem, I'll take it from here and get the adapter merged will let you know when it's merged, cheers.

**Comment by jpsains** [comment]
Hey @nickdoherty 

https://github.com/consensys-vertical-apps/mmi-defi-adapters/commit/dcc37dc2f7cc708b20de748a53be74543a25c35a rocket-pool adapter has been merged, thanks for your PR.

We also support APR I notice you have it on your UI, how does your UI calculate APR? Can you share the code, please? Cheers :) 

image

Im going to close this PR now since we cheery picked the commit into main 👍

**Comment by nickdoherty** [comment]
Thank you @jpsains.

Our APR calculation requires the use of an Archive Node & some event queries.

We have an API for the value available at https://api.rocketpool.net/mainnet/reth/apr however in the adapter documentation it stated that API calls were frowned upon, so we didn't include it.

Would a simple API call be allowed?

**Pull request closed without merging**
